#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define MaxS 4096
#define MaxN 100

long Xsize=80, Ysize=80, Zsize=80;
float X0, Y0, Z0;
float dX,dY,dZ;
long NAtom=0;
float V1[MaxN*MaxN*MaxN], V2[MaxN*MaxN*MaxN];

void fgetstr(FILE *f, char *s)
{
 long n=0;
 while(!feof(f)) 
  {
   s[n]=fgetc(f);
   if(s[n]=='\n') break; 
   if(s[n]!=EOF) n++;
   if(n>=MaxS) {s[n]='\0';break;}
  }
 s[n]='\0';
}

float Compare_Vol_Data(float *m1, float *m2) {
  long x,y,z;
  float Sum=0, v1, v2;

  for (x=0; x<Xsize; x++)
    for (y=0; y<Ysize; y++)
      for (z=0; z<Zsize; z++) {
        v1=m1[z*Xsize*Ysize + y*Xsize + x];
        v2=m2[z*Xsize*Ysize + y*Xsize + x];
        Sum+=fabs(v1*v1-v2*v2);
      }

//  printf("Delta = %f\n", Sum);
  printf("%f", Sum);
  return Sum;
}

int Read_Vol_Data(FILE *f, float *m) {
  long x,y,z;
  float v;

  for (x=0; x<Xsize; x++)
    for (y=0; y<Ysize; y++) { // printf("{%ld %ld}  ", x+1, y+1);
      for (z=0; z<Zsize; z++) {
        if (fscanf(f, "%f", &v) != 1) return -1; else m[z*Xsize*Ysize + y*Xsize + x]=v;
//        printf("%ld[%e] ", z+1, m[z*Xsize*Ysize + y*Xsize + x]);
      }
//      printf("\n");
    }

  return 0;
}

int Read_Gaussian_Cube(char *FName, float *m) {
  char s[MaxS];
  FILE *f;
  long n,i;
  float d;

  f=fopen(FName,"r"); if(f==NULL) { printf("File [%s] not exist\n", FName); return -1; }
  fgetstr(f,s);
  fgetstr(f,s);
  fscanf(f,"%ld",&n); NAtom=-n;
  fscanf(f,"%f",&X0); fscanf(f,"%f",&Y0); fscanf(f,"%f",&Z0);
//  printf("NAtom=%ld X0=%f Y0=%f Z0=%f\n", NAtom, X0, Y0, Z0);
  fscanf(f,"%ld",&Xsize); fscanf(f,"%f",&dX); fscanf(f,"%f",&d); fscanf(f,"%f",&d);
  fscanf(f,"%ld",&Ysize); fscanf(f,"%f",&d); fscanf(f,"%f",&dY); fscanf(f,"%f",&d);
  fscanf(f,"%ld",&Zsize); fscanf(f,"%f",&d); fscanf(f,"%f",&d); fscanf(f,"%f",&dZ);
//  printf("DIM=(%ld %ld %ld) d=(%f %f %f)\n", Xsize, Ysize, Zsize, dX, dY, dZ);
  fgetstr(f,s); // printf("[%s]\n", s);
  for(i=0; i<NAtom; i++) fgetstr(f,s);
  fgetstr(f,s); // printf("[%s]\n", s);
  Read_Vol_Data(f, m);
  fclose(f);
}


int main(int argc, char *argv[]) {
  Read_Gaussian_Cube(argv[1], V1);
  Read_Gaussian_Cube(argv[2], V2);
  Compare_Vol_Data(V1, V2);
}

//Cube data generated by ORCA
//Molecular orbital 7 of operator 0
//   -5   -7.253245  -14.534962   -8.488432
//   80    0.199181    0.000000    0.000000
//   80    0.000000    0.296262    0.000000
//   80    0.000000    0.000000    0.217571
//    7    7.000000    1.166571   -5.470184    0.105687
//    7    7.000000    1.482018   -7.534962    0.105638
//    7    7.000000    0.942897    1.865592    0.106541
//    1    1.000000   -0.253245    1.869470    1.699690
//    1    1.000000   -0.250807    1.869728   -1.488432
//    1    7
//  -2.34491E-08  -2.75418E-08  -3.22585E-08  -3.76694E-08  -4.38470E-08  -5.08648E-08
